// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edkorswmkdkzfwnrilan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVka29yc3dta2RremZ3bnJpbGFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTI5MDQsImV4cCI6MjA2NzE2ODkwNH0.J26AflA1fNAtXsh5yRTkIdAvEbO6HjUTSnUb9DIe1WU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});